// -------------------------------------------------------------
// 
// File Name: hdlsrc\edgeDetector\CompareToThreshold.v
// Created: 2024-05-06 23:19:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CompareToThreshold
// Source Path: edgeDetector/EdgeDetection/CompareToThreshold
// Hierarchy Level: 1
// Model version: 1.2
// 
// -------------------------------------------------------------
/*


This requires a total rewrite as it is using floating point values for some reason :)

This modules takes in data, compares it to a constant value (as set per user) and then outputs 1 or zero depending if it exceeds
the threshold or not

*/


module CompareToThreshold
          (In1,
           u);


  input   [7:0] In1;  // uint8
  output  [63:0] u;  // double


  wire switch_compare_1;
  wire [63:0] Zero_out1;  // ufix64
  wire [63:0] Constant_out1;  // ufix64
  wire [63:0] Switch_out1;  // ufix64


  assign switch_compare_1 = In1 > 8'b00000001;



  assign Zero_out1 = 64'h0000000000000000;


  assign Constant_out1 = 64'h3ff0000000000000;


  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Zero_out1 :
              Constant_out1);


  assign u = Switch_out1;

endmodule  // CompareToThreshold

