// -------------------------------------------------------------
// 
// File Name: hdlsrc\edgeDetector\CompareToThreshold.v
// Created: 2024-05-06 23:19:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CompareToThreshold
// Source Path: edgeDetector/EdgeDetection/CompareToThreshold
// Hierarchy Level: 1
// Model version: 1.2
// 
// -------------------------------------------------------------
/*


This requires a total rewrite as it is using floating point values for some reason :)

This modules takes in data, compares it to a constant value (as set per user) and then outputs 1 or zero depending if it exceeds
the threshold or not

*/


module CompareToThreshold
          (In1,
            enb,
            reset,
           u,
           clk
           );


  input wire clk;
  input wire reset;
  input wire enb;
  input   [7:0] In1;  // uint8
  output  reg u;  // double


  // internal registers need a counter to get rid of the intial values that will develop edges on start
  reg [7:0] intCount;


  wire switch_compare_1;
  wire  Zero_out1;  // ufix64
  wire  Constant_out1;  // ufix64
  wire  Switch_out1;  // ufix64
  
  assign switch_compare_1 = In1 > 8'b00001010; // need to see if we can try make a threshold that is dynamic



  assign Zero_out1 = 1'b0;


  assign Constant_out1 = 1'b1;

  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Zero_out1 :
              Constant_out1);

  initial begin 
    u <=0;
  end

  always@(posedge(reset)) begin
    intCount <=0;
  end

  always@(posedge clk) begin
    if((enb)&&(intCount > 4)) begin
      u <=  Switch_out1;
    end
    else begin
      u <= 0;
    end
    intCount <= intCount +1;
  end


/*
  assign u <= Switch_out1;
*/
endmodule  // CompareToThreshold

